sudo: false
language: ruby
rvm:
  - 2.0.0
  - 2.1.7
  - 2.2.4
  - 2.3.0
matrix:
  allow_failures:
    - rvm: rbx-2
  include:
    - rvm: rbx-2
      script: bundle exec rake spec
notifications:
  flowdock:
    secure: fSZxX5z3bHWT8aCFKBFrDDt5o3Jb6EFWcm+pAcMabpfDHc4iktWuCUlSM405798TRdKdws1A2RncQGYiQyLbqNvtLz48dvj4BxgYW7P/vg0koN+I/H2MjpZeuIQ7BRSEJIq2sAYNVya+hSil+SPEBMTngJiP6VYG0dm6fFnRkyk=
addons:
  code_climate:
    repo_token: 704eb62133d951ce460a6047a15a58e0a521aa20ec6a533fa7a37585f8a75602
after_success:
    - bundle exec codeclimate-test-reporter

